.github/workflows/reusable-industrial-ci-with-cache.yml

This would help raising awareness of breaking things downstream before actually releasing.
In the past we broke things downstream e.g. for ur_robot_driver or most recently webots. 
With this change we could add a set of downstream packages that we would like to check when introducing changes.
This could either be incorporated into all builds (in each PR) or into a separate workflow that e.g. runs on pushes to the main (or respective distro) branch. This would show unintentional API breaks and / or integration test failures before actually releasing things to the buildfarm.

Add possibility to specify a DOWNSTREAM_WORKSPACE with ici

---

.github/workflows/reusable-industrial-ci-with-cache.yml

This should allow to optionally change the TARGET_WORKSPACE variable for ICI.
As discussed in #2 
According to [this](https://github.com/ros-industrial/industrial_ci/blob/c2b7b619ba802b3c3ae95d400076f6e17a2d86c3/industrial_ci/src/run.sh#L45) it should work that way since
```
$ export TARGET_WORKSPACE=""
$ export TARGET_REPO_PATH="hello"
$ export TARGET_WORKSPACE=${TARGET_WORKSPACE:-$TARGET_REPO_PATH}
$ echo $TARGET_WORKSPACE
hello
$ export TARGET_WORKSPACE="world"
$ export TARGET_WORKSPACE=${TARGET_WORKSPACE:-$TARGET_REPO_PATH}
$ echo $TARGET_WORKSPACE
world
```

Add target_workspace to ICI workflow

---

.github/workflows/humble-binary-build.yml
.github/workflows/iron-binary-build.yml
.github/workflows/rolling-binary-build.yml
ros_controls.humble.repos
ros_controls.iron.repos
ros_controls.rolling.repos

This PR adds nightly builds for the complete control stack on all distros. This is part of #4 and probably superseeds most of https://github.com/ros-controls/control.ros.org/pull/244.

Build full stack

---

.github/workflows/reusable-build-coverage.yml

Uses the composite action introduced with #11
I'm not sure if we need the `CODECOV_TOKEN`:
https://github.com/codecov/codecov-action/blob/e0b68c6749509c5f83f984dd99a76a1c1a231044/action.yml#L5-L7
In some repositories we use it, in some we don't. 
I tried adding it as [described here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callsecrets) but got errors from the caller workflow from my fork (where I don't have/need this token).
This was tested successfully with https://github.com/ros-controls/control_toolbox/pull/188

Add reusable workflow for coverage build

---

.github/workflows/reusable-build-coverage.yml

By default, the pipeline returns success even if the upload fails. This is misleading in my opinion.

coverage: Fail CI if codecov-action fails

---

.github/dependabot.yml
.github/workflows/reusable-build-coverage.yml

Roll codecov-action back to v3

---

.github/workflows/reusable-rhel-binary-build.yml

Jobs failed today because the metadata was old and there was a new sync for humble+iron.
https://github.com/ros-controls/control_toolbox/pull/190#issuecomment-1962109021
Calling `dnf check-update` should fix this.

[RHEL] Run dnf check-update

---

.github/workflows/reusable-rhel-binary-build.yml

@fmauch neither am I experienced with RHEL ;)
`dnf check-update` has a nonzero exit code if there are updates -> causing the workflow to fail. 
There would be a `--refresh` option for `dnf install`, but I don't know how to pass that via rosdep.
https://github.com/ros-controls/ros2_controllers/actions/runs/8028858148/job/21943668352?pr=831#step:5:47

Don't fail on dnf check-update

---

.github/actions/set-package-list/action.yml
.github/workflows/reusable-build-coverage.yml

codecov did not work with the path I configured for the checkout. It seems that the custom action still works without giving the explict path to `colcon list` -> no need for the path -> lcov/codecov works with the default path without further changes.
https://github.com/ros-controls/control_toolbox/actions/runs/8070248887/job/22050684141
https://app.codecov.io/gh/ros-controls/control_toolbox/commit/f5277a3e01eaea3557651e5d66a178df56f002b7/tree

Fix paths for lcov/codecov

---

.github/workflows/reusable-build-coverage.yml

Since 4v this is required. For this to work, adding a `CODECOV_TOKEN` action secret needs to be added to the GH repository.
This should fix our problems on uploading the code coverage as discussed in https://github.com/ros-controls/control_toolbox/pull/188. Closes #15 
In the target repo a secret has to be added in the project settings:
**
**
The token can be extracted on codecov.io.

Add token instructions to codecov-action

---

.github/issue_template_failed_ci.md
.github/workflows/reusable-industrial-ci-with-cache.yml

This should add an issue like [this](https://github.com/fmauch/control_toolbox/issues/15) when the ICI fails in a scheduled build.
See workflow run [here](https://github.com/fmauch/control_toolbox/actions/runs/8086943802/job/22100169616), where I artificially introduced a build error.
The issues data could be modified (title, labels, description...) but I would need input for that.

Automatically create an Issue on failed scheduled builds

---

.github/actions/set-package-list/action.yml

A small change to the action, if no path is given.
`colcon list --paths /* --names-only` would parse the whole file system otherwise.
See 
https://github.com/ros-controls/kinematics_interface/actions/runs/8108814658/job/22163280164

Fix colcon list action

---

.github/workflows/reusable-update-pre-commit.yml

[CI pipeline is not triggered for github-actions bot with GITHUB_TOKEN ](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow)
> When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN, with the exception of workflow_dispatch and repository_dispatch, will not create a new workflow run.
It can happen now that pre-commit fails after an update, e.g., see [here](https://github.com/ros-controls/ros2_control_demos/actions/runs/8230532691).
I don't know how to fix this, we probably would need to create separate tokens for this workflow?
Maintainers can manually run the work due to the workflow-dispatch trigger on the newly created PR, but this won't be listed in the PR. I propose making …

Pre-commit update: Add ref for scheduled build and hint for maintainers

---

.github/workflows/reusable-reviewer-lottery.yml

PR's generated from the workflows have `github-actions[bot]`, like the pre-commit update job.

Don't run reviewer lottery for `github-actions[bot]`

---

ros_controls.rolling.repos

Gazebo classic will never be released for Ubuntu noble.

Remove gazebo_ros2_control from rolling build

---

.github/workflows/reusable-debian-build.yml
.github/workflows/reusable-rhel-binary-build.yml

As discussed in the WG meeting on April 10th: set the test step `continue-on-error: false` for debian and RHEL workflows, because most of the ubuntu jobs are failing atm.

Remove continue-on-error for debian/rhel

---

.github/workflows/reusable-build-coverage.yml

Adding a temporary fix for rosdep+jammy+rolling until noble is fully released, see https://docs.ros.org/en/rolling/How-To-Guides/Using-Custom-Rosdistro.html
Removing `required-ros-distributions` for setup-ros was necessary, otherwise rosdep still didn't work.

Fix coverage build on rolling (temporarily)

---

.github/workflows/reusable-rosdoc2.yml

Since yesterday a new release of sphinx is out -> it is not compatible with breathe, following in failing rosdoc2 builds 
https://github.com/breathe-doc/breathe/issues/981
https://github.com/sphinx-doc/sphinx/pull/12298/files
https://github.com/ros-controls/realtime_tools/actions/runs/8716929711/job/23911232320?pr=161

Freeze the version of sphinx

---

.github/workflows/ci-pre-commit.yml
.github/workflows/reusable-build-coverage.yml
.github/workflows/reusable-pre-commit.yml
.github/workflows/reusable-ros-tooling-source-build.yml
.github/workflows/reusable-update-pre-commit.yml
.pre-commit-config.yaml

Using the last version of setup-ros fixed it for noble, if the correct container is used. These PR adds changes for all usages of setup-ros to make that work for our workflows.
Needs `container: ubuntu:24.04` until the github runner will be updated, but the workflows should work automatically if ubuntu-latest is bumped to 24.04 and no `container` input is given.
Fixes #51 and #13

Updates for noble

---

.github/workflows/reusable-pre-commit.yml

I changed the checkout path, but haven't updated the path for the hash function
`Cache restored from key: pre-commit|rolling|dc522a5d8b78c8cffc118fef77b9040b7e00a53dc32dc8c1d883cb88c641c9a0`

Fix pre-commit cache

---

.github/workflows/reusable-build-coverage.yml
.github/workflows/reusable-pre-commit.yml
.github/workflows/reusable-ros-tooling-source-build.yml

(some?) core packages are already pre-released on testing repo for jazzy. Does it make sense to use testing as default for
- pre-commit
- coverage
- source
workflows? I think yes.

Use testing repo for setup-ros

---

.github/workflows/ci-pre-commit.yml
.github/workflows/reusable-pre-commit.yml

As [ros:jazzy](https://discourse.ros.org/t/save-the-date-jazzy-jalisco-testing-and-tutorial-party-2024-05-01/37155/20) is available, we can use it and install ros only optionally -> way faster
Calling workflows do not fail if inputs are set which aren't available (no need to change every usage of reusable-pre-commit now).

Use official ros images for pre-commit

---

.github/workflows/reusable-build-coverage.yml

As with realtime_tools, there is no need for repos file because there are no dependencies, see the comment from @saikishor in https://github.com/ros-controls/realtime_tools/pull/165
All workflows do work without a repos file, except for the coverage build expecting a repos file for the distro in the main directory. I made that optional, without the need of changing all calling workflows by adding the repos file as inputs
Repo without repos file: https://github.com/ros-controls/realtime_tools/actions/runs/8878232544/job/24373456071
Repo with repos file: https://github.com/ros-controls/control_toolbox/actions/runs/8878352900/job/24374164258

Coverage-build: Make repos file optional

---

ros_controls.rolling-on-humble.repos
ros_controls.rolling-on-iron.repos

I'd suggest to deactivate the build of gz_ros2_control in the compatibility build until https://github.com/ros-controls/ros2_control_ci/pull/77 is fixed (which might be never), to test at least the core packages for compatibility.

Deactivate gz_ros2_control compatibility build

---

.github/workflows/humble-binary-build.yml
.github/workflows/iron-binary-build.yml
.github/workflows/jazzy-binary-build.yml
.github/workflows/rolling-binary-build.yml
.github/workflows/rolling-compatibility-humble-binary-build.yml
.github/workflows/rolling-compatibility-iron-binary-build.yml
.github/workflows/rolling-compatibility-jazzy-binary-build.yml
README.md
ros_controls.rolling-on-jazzy.repos

- gazebo classic is not released on noble -> gazebo_ros2_control can't be compiled on jazzy/noble
- reformat README
- add path filters, run PRs if repos/yaml files have changed

Fix jazzy tests and other minor workflow changes

---

.github/workflows/reusable-build-coverage.yml

This is necessary to get branch coverage of python files called within c++ tests.

Adds coverage.py

---

ros_controls.rolling-on-jazzy.repos
ros_controls.rolling.repos

https://github.com/ros-controls/gz_ros2_control/pull/408#pullrequestreview-2260392863

gz_ros2_control: Use renamed rolling branch

---

.github/workflows/reusable-ros-tooling-source-build.yml
defaults.yaml

Test stage of source builds fail regularily, like https://github.com/ros-controls/ros2_controllers/issues/1299
The log is very confusing, then I realized that the action-ros-ci runs the tests in parallel, while ICI uses `--executor sequential` argument. I added a defaults yaml for the action-ros-ci, which should improve this
https://colcon.readthedocs.io/en/released/reference/executor-arguments.html
https://github.com/ros-tooling/action-ros-ci/blob/3e19c804cebf096f76de1b07ddd1cb52b5a2b8e3/action.yml#L8C3-L8C19

Add a defaults.yaml file for source build

---

.github/workflows/reusable-abi-check.yml
.github/workflows/reusable-build-coverage.yml
.github/workflows/reusable-industrial-ci-with-cache.yml
.github/workflows/reusable-rosdoc2.yml

- add a reusable workflow for ABI check (and use https://github.com/sloretz/ros_oci_images/)
- coverage-build: use https://github.com/sloretz/ros_oci_images/ and always use testing branch
- ici (used for binary and semi-binary builds): use https://github.com/sloretz/ros_oci_images/
- rosdoc2: Use ros:rolling instead of bare ubuntu image
This saves a minute here and there, especially when using `act` locally when the docker images are pulled already.
Tested with https://github.com/ros-controls/control_toolbox/pull/216

Use ros images where possible

---

.github/workflows/reusable-debian-build.yml
.github/workflows/reusable-rhel-binary-build.yml

We don't get the error logs from `colcon test-result`, see this job https://github.com/ros-controls/ros2_control/actions/runs/11710512553/attempts/2
`continue-on-error` is not well documented, but maybe this is why it doesn't complete the run steps.

Run test-result if colcon test failed

---

.github/workflows/reusable-ros-tooling-win-build.yml

- setup-ros has hardcoded python 3.8, as it is the default version acc. to REP-2000 for jazzy
- whatever I tried, python 3.12 is selected by action-ros-ci
- action-ros-ci uses cmd.exe -> Git\bin\bash.exe, which gives the correct version in the first step, but
- ament_cmake is always finding the newest python version -> dependencies are not installed
See also https://github.com/ros2/ros2/issues/1430#issuecomment-1634580503
--> the only working solution I've found is to remove the other python versions first.

Add reusable workflow for windows CI

---

.github/workflows/reusable-industrial-ci-with-cache.yml

We had warnings from upstream packages passing to our builds, resulting in [clang jobs to fail](https://github.com/ros-controls/ros2_control/actions/runs/12244504697/job/34156383141?pr=1918)
I propose excluding all system headers from these checks
see https://clang.llvm.org/docs/UsersManual.html#controlling-diagnostics-in-system-headers

Mark everything under /opt/ros a system header

---

.github/workflows/reusable-ros-tooling-win-build.yml

Needed to install ros/filters or https://github.com/ros-controls/realtime_tools/pull/253
https://github.com/MarkusJx/install-boost

Add boost to windows workflow

---

.github/workflows/build_and_publish_debian_docker.yaml
.github/workflows/build_and_publish_rhel_docker.yaml
.pre-commit-config.yaml
README.md
ros2_debian/Dockerfile.debian11
ros2_debian/Dockerfile.debian12
ros2_debian/defaults.yaml
ros2_debian/ros-controls.humble.repos
ros2_debian/ros-controls.jazzy.repos
ros2_debian/ros-controls.rolling.repos
ros2_debian/ros_entrypoint.sh
ros2_rhel/Dockerfile.rhel8
ros2_rhel/Dockerfile.rhel9
ros2_rhel/defaults.yaml
ros2_rhel/ros-controls.rhel8.repos
ros2_rhel/ros-controls.rhel9.repos
ros2_rhel/ros_entrypoint.sh

Github actions are automatically deactivated if the repository doesn't have any changes for 60 days. 
I propose to move all the docker images from the ros2_debian and ros2_rhel repo here, so we will hit this timeout very unlikely.
Additionally, I cleaned up the docker files and made zenoh compiling on debian12.

Add docker files for debian and rhel

---

.github/workflows/build_and_publish_ubuntu_docker.yaml
.github/workflows/reusable-abi-check.yml
.github/workflows/reusable-build-coverage.yml
.github/workflows/reusable-industrial-ci-with-cache.yml
.github/workflows/rolling-binary-build.yml
README.md
ros2_ubuntu/Dockerfile
ros2_ubuntu/ros_entrypoint.sh

As we recently had problems with the docker images in the workflows using main binaries (ABI break of fastcdr, see https://github.com/eProsima/Fast-CDR/issues/266), I want to use images with ros2-testing binaries. But there are none out there for all current distro, so let's create our own.
Tested with realtime_tools, and it works great!
https://github.com/ros-controls/realtime_tools/pull/313

Add our own Ubuntu docker images

---

ros2_ubuntu/Dockerfile

Since #300 the setup-ros setup is not executed any more with the coverage build, and the rosdep step is failing now.
Fixing this by bootstrapping rosdep already in the docker image.

Bootstrap rosdep

---

.github/workflows/reusable-ros-tooling-source-build.yml
ros_controls_source.rolling.repos

Fixes https://github.com/ros-controls/ros2_control/issues/2161 by using the [rosinstall_generato](https://github.com/ros-tooling/action-ros-ci/tree/0.4.1/?tab=readme-ov-file#build-with-a-custom-repos-or-rosinstall-file)r for creating all dependencies. (no need for ros2.repos any more).
Successfully tested with https://github.com/ros-controls/ros2_control/actions/runs/14400388586/job/40399334766
I also added the connext-dds to the rosdep-skip-keys, which fixes https://github.com/ros-controls/kinematics_interface/issues/130 and fixes https://github.com/ros-controls/realtime_tools/issues/312 and fixes https://github.com/ros-controls/ros2_control/issues/2170 and fixes https://github.com/ros-controls/ros2_controllers/issues/1633

Auto-generate dependencies for source build

---

.github/workflows/reusable-ros-tooling-source-build.yml

The new source build fails often because of 403 or 404 HTTP error (don't ask me if this is normal)
`urllib.error.HTTPError: HTTP Error 403: Forbidden (http://repo.ros2.org/rosdistro_cache/jazzy-cache.yaml.gz)`
We could simply retry it for a couple of minutes

rosinstall_generator fails regularily: retry for 5min

---

.github/workflows/reusable-debian-build.yml

This is to allow the debian jobs to install the dependencies before building and executing tests
Needed for https://github.com/ros-controls/ros2_control/pull/2202

Add install dependencies step for debian jobs

---

ros2_debian/ros-controls.jazzy.repos
ros2_debian/ros-controls.kilted.repos
ros2_debian/ros-controls.rolling.repos

See the failing jobs on https://github.com/ros-controls/control_toolbox/pull/364
is it good practice to use the release repos (would be more equivalent to ubuntu binary builds), or should we use the development branches (would be more equivalent to source builds) instead? Currently, we have a mixture.

Use bookworm releases instead of bullseye

---

ros2_debian/ros-controls.humble.repos
ros2_debian/ros-controls.jazzy.repos
ros2_debian/ros-controls.kilted.repos
ros2_debian/ros-controls.rolling.repos

followup to #336 
we could also use rosinstall_generator to generate the repos file, but leave it hardcoded as of now

Debian: Use release packages instead of development version

---

.github/reviewer-lottery.yml

It seems that @peterdavidfagan has left the reviewer group, and reviewer lottery is failing sometimes now
https://github.com/ros-controls/ros2_controllers/actions/runs/16469727572

Update reviewer lottery

---

.github/workflows/reusable-ros-tooling-source-build.yml

I've been using `reusable-ros-tooling-source-build.yml` workflow directly from this repo, but as my package has no dependencies declared in `package.xml`, the `.repos` file generated by `rosinstall_generator` is empty, causing `vcs import` to crash:
```
Invoking: bash -c,vcs import --force --recursive src/ --input file:///tmp/deps.repos
/usr/bin/bash -c vcs import --force --recursive src/ --input file:///tmp/deps.repos
/usr/bin/vcs:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
from pkg_resources import load_entry_point
Input data is not valid format: 'NoneType' object is not subscriptable
Error: The process '/usr/bin/bash' failed with exit code 1
```
Added a step which, if the generated `.repos` file is empty, …

check for empty .repos file to avoid vcs crashing

---

.github/workflows/reusable-ros-tooling-win-build.yml

We need to patch the ROS installation, otherwise python scripts don't work (like ros2cli).

Use rosinstall generator for windows workflow
